# PARAMETROS DE OPERACION BASE
MAX_GREEN = 45
MIN_GREEN = 10
YELLOW_DURATION = 3
ALL_RED_DURATION = 1

# CASO 5 - PESO VISUAL (segundos extra por tipo de vehiculo)
PESOS_VISUALES = {
    "moto": 2,
    "auto": 3,
    "bus": 5,
    "truck": 5,
    "ambulancia": 2,
    "patrullero": 2
}

# ANTI-STARVATION
STARVATION_LIMIT = 60

# CASO 3 - OCULSION
UMBRAL_OCLUSION = 3       # incremento minimo de conteo en historial para detectar occlusion
HISTORIAL_TAMANO = 10      # frames de historial

# CASO 4 - ESQUINA TRANCADA
TIEMPO_CONFIRMAR_CHOQUE = 15
VELOCIDAD_CHOQUE = 0.0

# CASO 6 - INUNDACION
VELOCIDAD_INUNDACION = 3.0  # km/h
TIEMPO_CONFIRMAR_INUNDACION = 15

# CASO 7 - CAMARA FALLADA
VENTANA_CIEGA = 30

# CASO 9 - MAQUINA DE ESTADOS
DT = 0.5

# PROBABILIDADES DE SIMULACION
PROB_SPAWN = 0.05
TASA_LIBERACION = 1
PROB_EMERGENCIA = 0.002
PROB_CAMARA_FALLA = 0.001
PROB_VEHICULO_PESADO = 0.2

# NOMBRES DE ACCESOS
NOMBRES_ACCESOS = {"N": "NORTE", "S": "SUR", "E": "ESTE", "O": "OESTE"}
